name: CICD Pipeline

on: 
  push:
    branches:
      - main  # Optionally specify the branch that triggers the pipeline.

jobs:
  CICD_Pipeline_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        # upload code on github
        uses: actions/checkout@v3
    
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with: 
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc mlflow  # Install DVC and MLflow explicitly if not in requirements.txt

      - name: login to docker
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/base2:latest .

      - name: Docker Push Image
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/base2:latest